### ISSUE TITLE
Change colors on the fly?

### ISSUE THREAD

**Issue by landorg** [wurosh/ewal#3]
Hi,
is it possible with this to change the colors on the fly? 
( I'm using a daemon setup )
If so: How can I do it from command line?
Thanks

**Comment by cyruseuros** [comment]
I've since stopped using emacs but you basically need to run `(load-theme 'ewal-<theme>)` and I seem to recall emacsclient being able to send s-expressions to emacs for evaluation from the CLI.

**Comment by landorg** [comment]
that works. 
Thanks :+1:
