### ISSUE TITLE
spacemacs-common was renamed to spacemacs-theme

### ISSUE THREAD

**Issue by tarsius** [wurosh/ewal#4]
See https://github.com/nashamri/spacemacs-theme/pull/63.

**Comment by cyruseuros** [comment]
unfortunately I migrated to helix + zellij from Emacs and can no longer maintain my packages - do let me know if you're interested in making the change

**Comment by tarsius** [comment]
> do let me know if you're interested in making the change

I'm interested :smiley:
See #5.

**Comment by cyruseuros** [comment]
Tested to work? I no longer have an Emacs/Spacemacs config to test with
